spring:
  datasource:
    username: user
    password: passwd
    url: "jdbc:postgresql://localhost:5432/adoptions"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update