spring:
  datasource:
    username: myuser
    password: db_usr_passwd
    url: "jdbc:postgresql://localhost:5432/adoptions"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
